import Foundation

enum CreditsArtists {
    static let all: [(String, String)] = [
        ("👽 (owo_uou)", "https://x.com/owo_uou"),
        ("109kpm", "https://space.bilibili.com/626515610"),
        ("5RI", "https://x.com/art5RI"),
        ("Ahche", "https://x.com/Ahchive_Be"),
        ("AlinFaeleas", "https://x.com/alinfaeleas"),
        ("Ame0", "https://x.com/HDaHrBUapT57ndh"),
        ("Amorous艾莫", "https://x.com/AmorousSuc"),
        ("Anima-trix", "https://x.com/animatrix30"),
        ("Aokuma", "https://x.com/aokuma_work"),
        ("AppleC", "https://x.com/AppL_CD"),
        ("Aserus 🐰🪽", "https://x.com/aserusg"),
        ("Asfie", "https://x.com/aesfixcia"),
        ("Astra", "https://x.com/astrachan949"),
        ("Augne", "https://x.com/Panneko_o"),
        ("Ayane Asamura", "https://x.com/l99ayane"),
        ("Bauka", "https://x.com/Baurz1"),
        ("Bitseon", "https://x.com/ksh02178"),
        ("Borzoi", "https://x.com/Deueeuui223"),
        ("CArroT", "https://space.bilibili.com/2038218765"),
        ("catt", "https://x.com/cattocut"),
        ("Chahan🍜", "https://x.com/ChahanRamen2"),
        ("Charismaju", "https://fiverr.com/studartsmaju"),
        ("Clover Dot", "https://x.com/Clov_erD"),
        ("Copper1ion", "https://x.com/Cooper1ion"),
        ("cosmicblubb", "https://x.com/cosmicblubb"),
        ("Dafalgan", "https://x.com/dafalgan09"),
        ("danieax", "https://x.com/DanieaxH"),
        ("DCMeC", "https://www.pixiv.net/users/105368797"),
        ("Diego", "https://x.com/DiegoIsADog_"),
        ("Donzduck", "https://x.com/JackTheFridge"),
        ("Douraze", "https://x.com/DourazeE57303"),
        ("Dreamplanes", "https://x.com/Dreamplanes256"),
        ("E20", "https://x.com/E20_loop"),
        ("eenightlamp", "https://x.com/eenightlamp"),
        ("EOcelot", "https://x.com/EggpieART"),
        ("Erina", "https://x.com/ErinaVtuber"),
        ("Fashae", "https://x.com/Fashaeli"),
        ("FeliXKohai", "https://x.com/FelixKohai"),
        ("fians", "https://x.com/fiansand"),
        ("FieryOnion", "https://x.com/moenaionion"),
        ("floofyjul", "https://linktr.ee/fluffysoraa"),
        ("foame", "https://x.com/foame_"),
        ("Frultea", "https://x.com/frultea_0312"),
        ("Fur31mu", "https://x.com/Fur31mu"),
        ("Gobackgu", "https://x.com/Gobackgu"),
        ("Goyu_Gy", "https://x.com/Goyu_Gy"),
        ("GuRara", "https://x.com/GuRara_31"),
        ("hachio", "https://x.com/hachio81"),
        ("Hanna.S", "https://x.com/HanaShi1821"),
        ("HatKD", "https://x.com/HatKD44"),
        ("heren", "https://x.com/herenjun666"),
        ("hoshistream", "https://x.com/Hoshistream"),
        ("idunno", "https://x.com/dgucedunno"),
        ("Izumi_", "https://x.com/Izumi_IND"),
        ("JIANGDAYU", "https://x.com/JDYDTG123"),
        ("Johnny's Garage", "https://x.com/JohnnyGarageAn"),
        ("K3tchup (tomatojam26)", "https://x.com/s_K3tchup"),
        ("kan", "https://x.com/kan1360"),
        ("kanna", "https://x.com/www88ex"),
        ("kaze", "https://x.com/koishiflandre1"),
        ("KeemunArt", "https://x.com/KeemunArt"),
        ("Key🦋 (soulgluttony)", "https://x.com/soulgluttony"),
        ("kisimaT_T", "https://x.com/kisimaT_T"),
        ("Kitsuneco", "https://x.com/kitsuneco12"),
        ("klef", "https://x.com/k_lef111256"),
        ("klmmox", "https://x.com/klmmox_"),
        ("Korei", "https://x.com/Koreillust"),
        ("KoyoriKei", "https://x.com/koyorikei"),
        ("KyaraShard", "https://x.com/KyaraShard"),
        ("Ladi", "https://x.com/LaaaaaDi_"),
        ("lappland987", "https://space.bilibili.com/588649898"),
        ("lenkyun02", "https://x.com/len_kyun02"),
        ("LEXingXD (lukuwo2333)", "https://x.com/lukuwo2333"),
        ("lightenbee", "https://x.com/lightenbee"),
        ("LILY", "https://x.com/hanabira06"),
        ("linhcoris", "https://x.com/linhcoris"),
        ("Lisa (lisadikaprio)", "https://x.com/LisadiKaprio"),
        ("Lst", "https://x.com/leafthreet"),
        ("LuLuLu", "https://x.com/Lucferz13"),
        ("Lunacy", "https://x.com/lunacy_420"),
        ("Luphine", "https://x.com/laLuphine"),
        ("Lynx", "https://x.com/lynxstellaa"),
        ("lyrly", "https://space.bilibili.com/603688153"),
        ("MaisatRaisat", "https://x.com/MaisatRaisat"),
        ("Mamiodapao_", "https://x.com/Mamiodapao_"),
        ("Mandradox", "https://x.com/mandradox"),
        ("Maruru Maru", "https://x.com/NotMaruMaruru00"),
        ("MaShiTaUU", "https://x.com/MaShiTaUU"),
        ("Miryang", "https://x.com/Miryang__"),
        ("miso", "https://x.com/yakuutgi"),
        ("Moneka", "https://x.com/Monikaphobia"),
        ("mr.fish399", "https://x.com/MrFish399"),
        ("mumuk沐沐", "https://space.bilibili.com/384458639"),
        ("Naham", "https://x.com/N4_H4M"),
        ("NANAKI54", "https://x.com/xiii_underblade"),
        ("Naofaro", "https://x.com/Naofaroo"),
        ("Nenemu🍓💤", "https://x.com/nenemu_55"),
        ("Nira (0nirauwu0)", "https://x.com/FreakyNira"),
        ("Nythlin", "https://x.com/NythlinVT"),
        ("Nyuakel", "https://x.com/nyuakel"),
        ("Olineeria", "https://x.com/olineeria"),
        ("onymki2", "https://x.com/_onymki2"),
        ("ORENJIINEKO", "https://x.com/orenjineko46873"),
        ("Origonz", "https://x.com/Origonz5"),
        ("P3R", "https://x.com/atari_desu"),
        ("paccha!! 🍕💜", "https://x.com/paccha_7"),
        ("Pchan", "https://x.com/pinkpink939"),
        ("petsuOnMars", "https://x.com/supapetsu"),
        ("philovyc_", "https://x.com/Philovyc_"),
        ("Pius", "https://x.com/kapxapius"),
        ("PTITSA QAQ", "https://x.com/PtitsaQAQ"),
        ("Railyx", "https://x.com/raily_x"),
        ("Rain", "https://x.com/Rain_Lambda"),
        ("RAITvisualworks", "https://x.com/RAITvisualworks"),
        ("realms (skyrealplane)", "https://x.com/skyrealplane"),
        ("Reivoon", "https://x.com/Reivooon"),
        ("reyforn", "https://x.com/reyforn_"),
        ("Rikkuchan", "https://x.com/rikkuchan_neru"),
        ("RocketDraft", "https://x.com/OKRocketBoy1"),
        ("Ruciel", "https://x.com/Ruxiyel"),
        ("rukooo", "https://x.com/ruruk_o2"),
        ("Rune", "https://x.com/000Rune000"),
        ("Sachi", "https://x.com/smelly_sachi"),
        ("SamSam", "https://x.com/Samsam_S2S"),
        ("sAvIor", "https://x.com/sAviOr4429"),
        ("Seeleゼーレ", "https://x.com/seelka_"),
        ("sena_ink", "https://bsky.app/profile/sena.ink"),
        ("Serafhin", "https://x.com/Serafhin1"),
        ("ShanderZone92", "https://facebook.com/shandi.hidayat"),
        ("Shinbaru", "https://x.com/_shinbaru"),
        ("shushiOwO", ""),
        ("Sink (sznkyuu_)", "https://x.com/sznkyuu"),
        ("sknh3", "https://x.com/sknhnhnh"),
        ("Slanter0116", "https://x.com/Slanter0116"),
        ("Sleepkms", "https://x.com/sleeprealsleep"),
        ("smillerbee", "https://x.com/smillerber1"),
        ("Sombinyl", "https://x.com/0419SBN"),
        ("Sugarph", "https://x.com/huedgehog"),
        ("Suge7", "https://space.bilibili.com/3546616711612831"),
        ("Sumi", "https://x.com/XHR6rZIxJiF1b1z"),
        ("suprii", "https://pixiv.net/en/users/10518285"),
        ("takeyabunora", "https://x.com/takeyabunora"),
        ("tanhuluu (food)", "https://x.com/tanhuluu"),
        ("Taprieiko", "https://x.com/Taprieiko"),
        ("TDA (tda.xd)", "https://x.com/tdaishomeless"),
        ("terrain", "https://x.com/terrainb52"),
        ("TheFatum", "https://x.com/thefatum0"),
        ("Tigera", "https://x.com/projectTiGER_"),
        ("Troobs", "https://x.com/TroobsART"),
        ("Tsp0615", "https://x.com/Tspchan1"),
        ("Ultimage", "https://x.com/UltimageYujin"),
        ("UsagiChuuu", "https://x.com/UsagiChuuu"),
        ("Void", "https://x.com/VoidSynatic"),
        ("Whiteくん", "https://x.com/White45838787"),
        ("Wimo", "https://x.com/wimowowo"),
        ("WindSketchy", "https://x.com/WindSketchy"),
        ("Wisteria", "https://wisteriavt-art.carrd.co"),
        ("Yaemaru Pie", "https://x.com/yaemaru_pie"),
        ("yumo", "https://x.com/yumo539959"),
        ("Yuuri", "https://x.com/0914yuuri_k"),
        ("Zerudawa", "https://x.com/Zerudawaa"),
        ("Zhafran", "https://x.com/zhafran_hfz"),
        ("Zinkaa", "https://x.com/zinkaaRT"),
        ("あおらいね🐟 (aoraineoekaki)", "https://x.com/aoraineoekaki"),
        ("アスカ (ASUKA10k)", "https://x.com/ASUKA10k"),
        ("いづ (noise__rxx)", "https://x.com/noise__rxx"),
        ("いわし (wawaisi_iwasi)", "https://x.com/wawaisi_iwasi"),
        ("うさみん (usamin)", "https://x.com/usamin1211"),
        ("えれ (erenshu)", "https://x.com/erenshu"),
        ("かむかむ (kamu_422)", "https://x.com/kamu_422"),
        ("キャリン", "https://x.com/_karyln"),
        ("くっしぃ (qussie)", "https://x.com/qussie"),
        ("くまたそ (gi_irst)", "https://x.com/gi_irst"),
        ("しえら (4ella)", "https://x.com/4ella_art"),
        ("すなお (sunao)", "https://x.com/sunao_no2"),
        ("ねこむ (iiii__gogo)", "https://x.com/iiii__gogo"),
        ("ぼちゃ𓃵", "https://x.com/Bocha_2_2"),
        ("ほてら🦋🍒 (HoujiTeaLatte)", "https://x.com/HoujiTeaLatte_"),
        ("みこし (mikoshi)", "https://x.com/mikoshi_illust"),
        ("やなぎ (Yanagi)", "https://x.com/WnjfNvku7lDvMv9"),
        ("ラテ🥛 (satera723)", "https://x.com/satera723"),
        ("乱码奔腾 [LUANMA]", "https://x.com/luanma96"),
        ("二十七度火", "https://space.bilibili.com/278484760"),
        ("六狸木芸窗", "https://space.bilibili.com/24521463/dynamic"),
        ("冰岩荔枝", "https://space.bilibili.com/485117171"),
        ("升由るむ🩵🍄 (Masuyu rumu)", "https://x.com/Masuyu_rumu"),
        ("吉_ヴィーナス", "https://space.bilibili.com/39188322/dynamic"),
        ("坂菜 𓈒𓏸*", "https://x.com/Sakana0610773"),
        ("字榎えの (uenoeno)", "https://x.com/uenoeno_"),
        ("宅笙Zhai_Sheng (ZS_IN_CHINA)", "https://x.com/ZS_IN_CHINA"),
        ("宇宙蹦迪秋莎 (Marisa Una)", "https://space.bilibili.com/11156485"),
        ("小月明酱", "https://space.bilibili.com/91397867"),
        ("山楂 (shanzha114514)", "https://x.com/shanzha114514"),
        ("巳蝰 (Bitis)", "https://space.bilibili.com/381660852"),
        ("忽悠 (kasoke)", "https://x.com/kasoke308"),
        ("成吉柯德1560", "https://space.bilibili.com/295017712"),
        ("日土葉 (hidzuchi)", "https://x.com/hidzuchi_18"),
        ("晓马LLK", "https://x.com/xiaomaCroz"),
        ("曦月_Gigetsu", "https://space.bilibili.com/12390629/dynamic"),
        ("水金属liquain", "https://x.com/liquain_"),
        ("泠喵喵i (lingmiaoi)", "https://x.com/lingmiaoooii"),
        ("炭块UwU", "https://space.bilibili.com/100840024"),
        ("炭烤龙尾巴", "https://space.bilibili.com/2108308"),
        ("瑟林SOREN", "https://x.com/sorenFTT"),
        ("真焕琴 (Neoriaquin)", "https://space.bilibili.com/484703647"),
        ("福沢 (yyy_fukuzawa)", "https://x.com/yyy_fukuzawa"),
        ("約Soku", "https://x.com/yuesoku_"),
        ("結木ユウ (Indigo Blue)", "https://x.com/Indigo_Blue_anp"),
        ("绢索 (Amogha_Pasa)", "https://x.com/Amogha_Pasa"),
        ("耶底底亚908", "https://space.bilibili.com/1774554671"),
        ("能天使--- (Goldenglow__)", "https://space.bilibili.com/367461513"),
        ("虚無のメメイラ (memeira)", "https://x.com/memeiradesuyo"),
        ("豚バラなすのポン酢仕立て (hknk_029)", "https://x.com/hknk_029"),
        ("近藤武枝 (condotakeshi)", "https://x.com/condotakeshi2"),
        ("鋭川する (kawasuru)", "https://x.com/kawasuru"),
        ("阮翊y (Ruan Yi)", "https://space.bilibili.com/1112728201"),
        ("零悠≡ω≡ (lingyou)", "https://x.com/lingyouzzz"),
    ]
}
