name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer

      - name: Archive iPhone
        run: |
          xcodebuild archive \
            -project Twinskaraoke.xcodeproj \
            -scheme "Twinskaraoke" \
            -archivePath build/iPhone.xcarchive \
            -destination "generic/platform=iOS" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Package Sideload-Friendly iPhone IPA
        run: |
          mkdir -p Payload
          cp -R build/iPhone.xcarchive/Products/Applications/*.app Payload/
          
          # --- I HOPE THIS IS A FIX ---
          # remove watchapp from iOS folder.
          # SHOULD fix WKCompanionAppBundleIdentifier error
          rm -rf Payload/*.app/Watch
          
          zip -q -r Twinskaraoke-iPhone-Sideload.ipa Payload
          mkdir -p output && mv Twinskaraoke-iPhone-Sideload.ipa output/

      - name: Upload iPhone IPA
        uses: actions/upload-artifact@v4
        with:
          name: Twinskaraoke-iPhone
          path: output/Twinskaraoke-iPhone-Sideload.ipa

      - name: Archive Watch
        run: |
          xcodebuild archive \
            -project Twinskaraoke.xcodeproj \
            -scheme "TwinskaraokeWatchApp" \
            -archivePath build/Watch.xcarchive \
            -destination "generic/platform=watchOS" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Package Watch IPA
        run: |
          rm -rf Payload
          mkdir -p Payload_Watch
          cp -R build/Watch.xcarchive/Products/Applications/*.app Payload_Watch/
          mv Payload_Watch Payload
          zip -q -r Twinskaraoke-Watch.ipa Payload
          mkdir -p output_watch && mv Twinskaraoke-Watch.ipa output_watch/

      - name: Upload Watch IPA
        uses: actions/upload-artifact@v4
        with:
          name: Twinskaraoke-Watch
          path: output_watch/Twinskaraoke-Watch.ipa
